project_id = "yxfyrfvgmoklgekxiewn"

[functions.create-super-admin]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.upload-document]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false
